template: Hello, %s!

database:
    driverClass: org.h2.Driver
    user: mraas
    password: mraas
    url: jdbc:h2:target/mraas

logging:
    level: INFO
    loggers:
        com.hpcloud.mraas: DEBUG
    console:
        enabled: true
        threshold: ALL

http:
    port: 8080
    adminPort: 8081
    maxThreads: 100
    minThreads: 5
